/**
 * STATINTEL competency ontology — v1, 60 leaf competencies.
 *
 * Domains and competency names follow the four domains named in the SIH 2026
 * problem statement. Course names and role titles are modelled on MoSPI /
 * NSSTA vocabulary.
 *
 * ⚠ BEFORE THE FINALE: replace the role titles, cadre names and course names
 * below with entries traced to the published NSSTA training calendars and the
 * ISS Probationary Training reference manual on mospi.gov.in. A MoSPI judge
 * recognises their own vocabulary instantly — and notices when it is invented.
 * Everything else in the file (structure, edges, half-lives) is sound as-is.
 */

export type Domain = 'STAT' | 'TECH' | 'GOVN' | 'BEHV';

export interface CompetencySeed {
  id: string;
  domain: Domain;
  area: string;
  nameEn: string;
  nameHi?: string;
  description: string;
  gsbpm?: string[];
  /** months; how fast unused skill fades. tools decay fast, methodology slowly */
  halfLife: number;
  estHours: number;
  anchors: [string, string, string, string]; // L1..L4
}

const C = (
  id: string,
  domain: Domain,
  area: string,
  nameEn: string,
  description: string,
  halfLife: number,
  estHours: number,
  anchors: [string, string, string, string],
  gsbpm: string[] = [],
  nameHi?: string,
): CompetencySeed => ({ id, domain, area, nameEn, description, halfLife, estHours, anchors, gsbpm, nameHi });

// Generic anchor generator for competencies whose ladder is conventional.
const ladder = (t: string): [string, string, string, string] => [
  `Can define ${t} and recognise where it applies.`,
  `Can apply ${t} on a prepared task under supervision.`,
  `Can apply ${t} independently on new work and judge the result.`,
  `Can set standards for ${t}, review others' work and train peers.`,
];

export const COMPETENCIES: CompetencySeed[] = [
  // ───────────────────────── STATISTICAL (22) ─────────────────────────
  C('STAT.FOUND.DESC', 'STAT', 'Foundations', 'Descriptive Statistics',
    'Summarising distributions: central tendency, dispersion, skewness, and choosing the right summary for the data at hand.',
    72, 6, ladder('descriptive summarisation'), ['5.6'], 'वर्णनात्मक सांख्यिकी'),
  C('STAT.FOUND.PROB', 'STAT', 'Foundations', 'Probability & Distributions',
    'Probability laws, random variables, and the common distributions underlying survey estimation.',
    72, 10, ladder('probability reasoning')),
  C('STAT.FOUND.INFER', 'STAT', 'Foundations', 'Statistical Inference',
    'Estimation, confidence intervals, hypothesis testing and the interpretation of statistical uncertainty.',
    66, 12, ladder('inference'), ['5.6']),
  C('STAT.SAMP.BASIC', 'STAT', 'Sampling', 'Sampling Fundamentals',
    'Sampling frames, sampling units, coverage, sampling vs non-sampling error.',
    60, 8, ladder('sampling fundamentals'), ['2.4', '4.1'], 'प्रतिचयन के मूल सिद्धांत'),
  C('STAT.SAMP.SRS', 'STAT', 'Sampling', 'Simple Random Sampling',
    'SRSWOR/SRSWR selection, estimation of means and totals, variance estimation.',
    60, 6, ladder('simple random sampling'), ['2.4']),
  C('STAT.SAMP.STRAT', 'STAT', 'Sampling', 'Stratified Sampling',
    'Designing strata, allocation schemes (proportional, Neyman, optimal), and variance estimation for stratified designs.',
    60, 10, [
      'Can define stratification and name common stratification variables used in Indian surveys.',
      'Can execute a stratified design given a prepared frame and an allocation rule.',
      'Can design strata and choose an allocation independently for a new survey.',
      'Can evaluate design efficiency against alternatives, document the methodology and train others.',
    ], ['2.4', '4.1'], 'स्तरीकृत प्रतिचयन'),
  C('STAT.SAMP.CLUSTER', 'STAT', 'Sampling', 'Cluster & Multistage Sampling',
    'Multi-stage designs as used in NSS rounds: FSU/USU selection, design effect, intra-class correlation.',
    60, 12, ladder('multistage sampling'), ['2.4', '4.1']),
  C('STAT.SAMP.WEIGHT', 'STAT', 'Sampling', 'Weighting & Estimation',
    'Design weights, non-response adjustment, post-stratification, calibration and replication variance.',
    54, 12, ladder('survey weighting'), ['5.4', '5.6']),
  C('STAT.SURV.DESIGN', 'STAT', 'Survey Methods', 'Survey Design',
    'End-to-end design of a statistical survey: objectives, concepts, coverage, reference period, instruments and estimation strategy.',
    60, 16, ladder('survey design'), ['2.1', '2.2', '2.4']),
  C('STAT.SURV.QUEST', 'STAT', 'Survey Methods', 'Questionnaire Design',
    'Question wording, response formats, schedule structure, cognitive testing and enumerator instructions.',
    60, 10, ladder('questionnaire design'), ['2.3']),
  C('STAT.SURV.FIELD', 'STAT', 'Survey Methods', 'Field Operations & Supervision',
    'Field planning, enumerator briefing, supervision, scrutiny of schedules and quality control during collection.',
    48, 12, ladder('field supervision'), ['4.3']),
  C('STAT.SURV.NONRESP', 'STAT', 'Survey Methods', 'Non-response & Imputation',
    'Measuring and reducing non-response; editing and imputation methods and their effect on estimates.',
    54, 10, ladder('non-response treatment'), ['5.3', '5.4']),
  C('STAT.NATACC.BASIC', 'STAT', 'National Accounts', 'National Accounts Fundamentals',
    'SNA concepts, institutional sectors, production and income approaches, the accounting identities.',
    84, 14, ladder('national accounts concepts')),
  C('STAT.NATACC.GDP', 'STAT', 'National Accounts', 'GDP Compilation',
    'Compiling GVA and GDP by economic activity, deflation, base year revision and benchmarking.',
    84, 20, ladder('GDP compilation'), ['5.5', '5.6']),
  C('STAT.PRICE.CPI', 'STAT', 'Price Statistics', 'Consumer Price Index',
    'CPI concepts and compilation: item baskets, weighting diagrams, price collection, index number formulae.',
    72, 14, ladder('CPI compilation'), ['5.5']),
  C('STAT.PRICE.WPI', 'STAT', 'Price Statistics', 'Producer & Wholesale Price Indices',
    'WPI/PPI construction, item selection, quality adjustment and linking of index series.',
    72, 12, ladder('producer price indices'), ['5.5']),
  C('STAT.LABOUR.PLFS', 'STAT', 'Labour Statistics', 'Labour Statistics & PLFS',
    'Labour force concepts (ICLS), activity status, LFPR/WPR/UR estimation and the PLFS design.',
    66, 14, ladder('labour force statistics'), ['2.2', '5.6']),
  C('STAT.AGRI', 'STAT', 'Domain Statistics', 'Agricultural Statistics',
    'Crop area and yield estimation, crop cutting experiments, land use statistics.',
    72, 12, ladder('agricultural statistics')),
  C('STAT.INDUS.ASI', 'STAT', 'Domain Statistics', 'Industrial Statistics & ASI',
    'Annual Survey of Industries frame, concepts, returns processing and IIP construction.',
    72, 12, ladder('industrial statistics')),
  C('STAT.SDG', 'STAT', 'Frameworks', 'SDG Indicator Framework',
    'The global and National Indicator Framework, tier classification, data sources and reporting obligations.',
    48, 10, ladder('SDG indicator reporting'), ['7.1']),
  C('STAT.META', 'STAT', 'Frameworks', 'Metadata Standards (SDMX/DDI)',
    'Structural and reference metadata, SDMX data structure definitions, DDI documentation and machine-readable dissemination.',
    54, 10, ladder('statistical metadata'), ['3.1', '7.2']),
  C('STAT.DQ', 'STAT', 'Frameworks', 'Data Quality Frameworks',
    'Quality dimensions (relevance, accuracy, timeliness, coherence), NQAF, quality reporting and quality gates in production.',
    60, 10, ladder('data quality assurance'), ['6.2', '8.1']),

  // ───────────────────────── TECHNICAL (18) ─────────────────────────
  C('TECH.SPREAD', 'TECH', 'Tools', 'Spreadsheet Analysis',
    'Structured spreadsheet work: lookups, pivot tables, validation and reproducible workbook design.',
    36, 6, ladder('spreadsheet analysis')),
  C('TECH.PY.BASIC', 'TECH', 'Programming', 'Python Fundamentals',
    'Python syntax, data types, control flow, functions and the standard library.',
    18, 20, ladder('Python programming'), [], 'पायथन के मूल सिद्धांत'),
  C('TECH.PY.DATA', 'TECH', 'Programming', 'Python for Data Analysis',
    'pandas and numpy for cleaning, reshaping, merging and summarising statistical datasets.',
    18, 24, ladder('data analysis in Python'), ['5.1', '5.4']),
  C('TECH.R.BASIC', 'TECH', 'Programming', 'R Fundamentals',
    'R syntax, vectors, data frames and the tidyverse idiom.',
    18, 18, ladder('R programming')),
  C('TECH.R.SURVEY', 'TECH', 'Programming', 'Survey Analysis in R',
    'Complex survey estimation in R: the survey package, design objects, replicate weights.',
    18, 14, ladder('survey estimation in R'), ['5.6']),
  C('TECH.SQL', 'TECH', 'Data Engineering', 'SQL & Relational Data',
    'Relational modelling, joins, aggregation, window functions and query performance.',
    24, 16, ladder('SQL')),
  C('TECH.STATA', 'TECH', 'Tools', 'Stata', 'Stata do-files, survey estimation commands and reproducible logs.', 24, 12, ladder('Stata')),
  C('TECH.SPSS', 'TECH', 'Tools', 'SPSS', 'SPSS syntax, data preparation and standard statistical procedures.', 24, 10, ladder('SPSS')),
  C('TECH.SAS', 'TECH', 'Tools', 'SAS', 'SAS data steps, PROC procedures and large-file handling.', 24, 12, ladder('SAS')),
  C('TECH.GIS', 'TECH', 'Spatial', 'GIS & Spatial Statistics',
    'Coordinate systems, spatial joins, choropleth mapping and geo-referenced survey frames.',
    24, 18, ladder('GIS'), ['4.1']),
  C('TECH.VIZ', 'TECH', 'Analysis', 'Data Visualization',
    'Choosing and building charts that communicate a statistical finding accurately and accessibly.',
    30, 10, ladder('data visualisation'), ['7.2']),
  C('TECH.ML.BASIC', 'TECH', 'AI/ML', 'Machine Learning Foundations',
    'Supervised and unsupervised learning, training/validation discipline, bias-variance, evaluation metrics.',
    18, 24, ladder('machine learning')),
  C('TECH.ML.APPLIED', 'TECH', 'AI/ML', 'Applied ML for Official Statistics',
    'ML in the statistical production process: editing and imputation, coding of open text, nowcasting, and the quality/explainability constraints that apply to official output.',
    18, 20, ladder('applied ML in official statistics'), ['5.2', '5.3']),
  C('TECH.BIGDATA', 'TECH', 'Data Engineering', 'Big Data Processing',
    'Working with data too large for a single machine: partitioning, columnar formats, distributed processing.',
    18, 18, ladder('big data processing')),
  C('TECH.CLOUD', 'TECH', 'Infrastructure', 'Cloud Computing',
    'Cloud service models, compute and storage services, cost and capacity basics.',
    18, 14, ladder('cloud computing')),
  C('TECH.API', 'TECH', 'Data Engineering', 'APIs & Data Exchange',
    'REST concepts, authentication, pagination, and consuming or publishing statistical data through APIs.',
    24, 10, ladder('APIs'), ['7.2']),
  C('TECH.OPENDATA', 'TECH', 'Dissemination', 'Open Data & Dissemination',
    'Open data licensing, machine-readable publication, NDAP/data.gov.in workflows and user support.',
    36, 8, ladder('open data publication'), ['7.1', '7.3']),
  C('TECH.VERSION', 'TECH', 'Practice', 'Version Control & Reproducibility',
    'Git, reproducible pipelines and the discipline that lets a published figure be regenerated from source.',
    24, 8, ladder('reproducible workflows')),

  // ───────────────────────── DIGITAL GOVERNANCE (10) ─────────────────────────
  C('GOVN.CYBER', 'GOVN', 'Security', 'Cybersecurity Fundamentals',
    'Threat awareness, secure authentication, safe handling of official data and incident reporting duties.',
    30, 8, ladder('cyber hygiene')),
  C('GOVN.PRIVACY', 'GOVN', 'Legal', 'Data Privacy & DPDP Act 2023',
    'Personal data obligations under the DPDP Act: purpose limitation, minimisation, consent and the rights of data principals.',
    42, 8, ladder('data privacy obligations')),
  C('GOVN.CONFID', 'GOVN', 'Legal', 'Statistical Confidentiality & Disclosure Control',
    'Legal confidentiality of returns, statistical disclosure control methods and safe release of microdata.',
    60, 10, ladder('disclosure control'), ['6.4', '7.2']),
  C('GOVN.DSC', 'GOVN', 'Security', 'Digital Signatures & PKI',
    'Digital signature certificates, e-Sign, and the legal status of digitally signed records.',
    36, 4, ladder('digital signatures')),
  C('GOVN.CLOUD', 'GOVN', 'Infrastructure', 'Government Cloud (MeghRaj)',
    'GI Cloud / NIC hosting, empanelment, data localisation and the process to onboard an application.',
    30, 6, ladder('government cloud')),
  C('GOVN.DPI', 'GOVN', 'Platforms', 'Digital Public Infrastructure',
    'India Stack building blocks and how statistical systems interoperate with them.',
    30, 6, ladder('DPI')),
  C('GOVN.RTI', 'GOVN', 'Legal', 'RTI & Official Records',
    'RTI obligations and exemptions, records management and the handling of classified statistical material.',
    60, 6, ladder('RTI and records handling')),
  C('GOVN.EOFFICE', 'GOVN', 'Operations', 'e-Office & Digital Workflow',
    'File handling in e-Office, digital noting, and moving a departmental process off paper.',
    36, 4, ladder('e-Office')),
  C('GOVN.PROCURE', 'GOVN', 'Operations', 'GeM & IT Procurement',
    'Procuring IT goods and services through GeM, writing technical specifications and evaluating bids.',
    48, 8, ladder('IT procurement')),
  C('GOVN.AUDIT', 'GOVN', 'Compliance', 'Audit & Compliance Readiness',
    'Maintaining an audit trail, responding to audit observations and evidencing process compliance.',
    60, 6, ladder('audit readiness'), ['8.1']),

  // ───────────────────────── BEHAVIOURAL (10) ─────────────────────────
  C('BEHV.COMM', 'BEHV', 'Communication', 'Written Communication',
    'Drafting notes, reports and official correspondence that are precise and readable.',
    120, 6, ladder('official writing')),
  C('BEHV.PRESENT', 'BEHV', 'Communication', 'Data Storytelling & Presentation',
    'Presenting statistical findings to non-technical decision makers without distorting them.',
    96, 8, ladder('presenting data'), ['7.3']),
  C('BEHV.LEAD', 'BEHV', 'Leadership', 'Team Leadership',
    'Setting direction, delegating, giving feedback and holding a team to a standard.',
    120, 10, ladder('team leadership')),
  C('BEHV.PM', 'BEHV', 'Management', 'Project Management',
    'Planning, sequencing, resourcing and tracking a survey or IT project to a deadline.',
    96, 12, ladder('project management')),
  C('BEHV.ETHICS', 'BEHV', 'Integrity', 'Statistical Ethics & Integrity',
    'Professional independence, impartiality, and the Fundamental Principles of Official Statistics in daily practice.',
    120, 6, ladder('statistical ethics')),
  C('BEHV.DECIDE', 'BEHV', 'Management', 'Evidence-Based Decision Making',
    'Framing a decision, weighing evidence and uncertainty, and recording the basis of a decision.',
    96, 8, ladder('evidence-based decisions')),
  C('BEHV.CHANGE', 'BEHV', 'Management', 'Change Management',
    'Introducing a new method or system into an established office and carrying the staff with it.',
    96, 8, ladder('change management')),
  C('BEHV.STAKE', 'BEHV', 'Communication', 'Stakeholder Coordination',
    'Working across divisions, states and line ministries to get data and agreement.',
    96, 8, ladder('stakeholder coordination')),
  C('BEHV.TRAIN', 'BEHV', 'Leadership', 'Training & Mentoring',
    'Designing and delivering training, and developing junior staff on the job.',
    96, 10, ladder('training delivery')),
  C('BEHV.TIME', 'BEHV', 'Management', 'Work Planning & Prioritisation',
    'Planning own and team workload against competing deadlines.',
    120, 4, ladder('work planning')),
];

// ── edges ────────────────────────────────────────────────────────────────
// [from, to, kind, weight?, minFromLevel?]
// REQUIRES: `from` is a prerequisite of `to`.
// SUBSUMES: mastery of `from` gives partial credit in `to`.
// ADJACENT: transferable, weighted 0..1.
type EdgeTuple = [string, string, 'REQUIRES' | 'SUBSUMES' | 'ADJACENT', number?, number?];

export const EDGES: EdgeTuple[] = [
  // statistical spine
  ['STAT.FOUND.DESC', 'STAT.FOUND.PROB', 'REQUIRES'],
  ['STAT.FOUND.PROB', 'STAT.FOUND.INFER', 'REQUIRES'],
  ['STAT.FOUND.DESC', 'STAT.SAMP.BASIC', 'REQUIRES', 1, 1],
  ['STAT.FOUND.PROB', 'STAT.SAMP.SRS', 'REQUIRES'],
  ['STAT.SAMP.BASIC', 'STAT.SAMP.SRS', 'REQUIRES'],
  ['STAT.SAMP.SRS', 'STAT.SAMP.STRAT', 'REQUIRES'],
  ['STAT.SAMP.SRS', 'STAT.SAMP.CLUSTER', 'REQUIRES'],
  ['STAT.SAMP.STRAT', 'STAT.SAMP.WEIGHT', 'REQUIRES'],
  ['STAT.SAMP.CLUSTER', 'STAT.SAMP.WEIGHT', 'REQUIRES'],
  ['STAT.FOUND.INFER', 'STAT.SAMP.WEIGHT', 'REQUIRES'],
  ['STAT.SAMP.STRAT', 'STAT.SURV.DESIGN', 'REQUIRES'],
  ['STAT.SAMP.CLUSTER', 'STAT.SURV.DESIGN', 'REQUIRES'],
  ['STAT.SURV.QUEST', 'STAT.SURV.DESIGN', 'REQUIRES', 1, 1],
  ['STAT.SAMP.BASIC', 'STAT.SURV.FIELD', 'REQUIRES', 1, 1],
  ['STAT.SURV.QUEST', 'STAT.SURV.FIELD', 'REQUIRES', 1, 1],
  ['STAT.FOUND.INFER', 'STAT.SURV.NONRESP', 'REQUIRES'],
  ['STAT.SAMP.WEIGHT', 'STAT.SURV.NONRESP', 'REQUIRES', 1, 1],
  ['STAT.NATACC.BASIC', 'STAT.NATACC.GDP', 'REQUIRES'],
  ['STAT.FOUND.DESC', 'STAT.PRICE.CPI', 'REQUIRES', 1, 1],
  ['STAT.SAMP.BASIC', 'STAT.PRICE.CPI', 'REQUIRES', 1, 1],
  ['STAT.PRICE.CPI', 'STAT.PRICE.WPI', 'REQUIRES', 1, 1],
  ['STAT.PRICE.WPI', 'STAT.NATACC.GDP', 'REQUIRES', 1, 1],
  ['STAT.SURV.DESIGN', 'STAT.LABOUR.PLFS', 'REQUIRES', 1, 1],
  ['STAT.SAMP.WEIGHT', 'STAT.LABOUR.PLFS', 'REQUIRES', 1, 1],
  ['STAT.SURV.DESIGN', 'STAT.AGRI', 'REQUIRES', 1, 1],
  ['STAT.SURV.DESIGN', 'STAT.INDUS.ASI', 'REQUIRES', 1, 1],
  ['STAT.DQ', 'STAT.SDG', 'REQUIRES', 1, 1],
  ['STAT.META', 'STAT.SDG', 'REQUIRES', 1, 1],
  ['STAT.FOUND.INFER', 'STAT.DQ', 'REQUIRES', 1, 1],
  // subsumption: the advanced case covers the simpler one
  ['STAT.SAMP.STRAT', 'STAT.SAMP.SRS', 'SUBSUMES'],
  ['STAT.SAMP.CLUSTER', 'STAT.SAMP.SRS', 'SUBSUMES'],
  ['STAT.SURV.DESIGN', 'STAT.SURV.QUEST', 'SUBSUMES'],
  ['STAT.NATACC.GDP', 'STAT.NATACC.BASIC', 'SUBSUMES'],
  ['STAT.FOUND.INFER', 'STAT.FOUND.PROB', 'SUBSUMES'],
  ['TECH.PY.DATA', 'TECH.PY.BASIC', 'SUBSUMES'],
  ['TECH.R.SURVEY', 'TECH.R.BASIC', 'SUBSUMES'],
  ['TECH.ML.APPLIED', 'TECH.ML.BASIC', 'SUBSUMES'],
  // adjacency: transferable skill
  ['TECH.PY.BASIC', 'TECH.R.BASIC', 'ADJACENT', 0.75],
  ['TECH.PY.DATA', 'TECH.R.SURVEY', 'ADJACENT', 0.7],
  ['TECH.STATA', 'TECH.SPSS', 'ADJACENT', 0.65],
  ['TECH.SPSS', 'TECH.SAS', 'ADJACENT', 0.6],
  ['TECH.STATA', 'TECH.R.SURVEY', 'ADJACENT', 0.55],
  ['TECH.SPREAD', 'TECH.SQL', 'ADJACENT', 0.4],
  ['STAT.PRICE.CPI', 'STAT.PRICE.WPI', 'ADJACENT', 0.7],
  ['STAT.AGRI', 'STAT.INDUS.ASI', 'ADJACENT', 0.45],
  ['GOVN.CYBER', 'GOVN.PRIVACY', 'ADJACENT', 0.45],
  ['GOVN.PRIVACY', 'GOVN.CONFID', 'ADJACENT', 0.6],
  ['BEHV.LEAD', 'BEHV.TRAIN', 'ADJACENT', 0.55],
  ['BEHV.COMM', 'BEHV.PRESENT', 'ADJACENT', 0.6],
  // technical spine
  ['TECH.PY.BASIC', 'TECH.PY.DATA', 'REQUIRES'],
  ['TECH.R.BASIC', 'TECH.R.SURVEY', 'REQUIRES'],
  ['STAT.SAMP.WEIGHT', 'TECH.R.SURVEY', 'REQUIRES', 1, 1],
  ['TECH.SPREAD', 'TECH.PY.BASIC', 'REQUIRES', 1, 1],
  ['TECH.PY.DATA', 'TECH.ML.BASIC', 'REQUIRES'],
  ['STAT.FOUND.INFER', 'TECH.ML.BASIC', 'REQUIRES', 1, 1],
  ['TECH.ML.BASIC', 'TECH.ML.APPLIED', 'REQUIRES'],
  ['STAT.DQ', 'TECH.ML.APPLIED', 'REQUIRES', 1, 1],
  ['TECH.SQL', 'TECH.BIGDATA', 'REQUIRES'],
  ['TECH.PY.DATA', 'TECH.BIGDATA', 'REQUIRES', 1, 1],
  ['TECH.CLOUD', 'TECH.BIGDATA', 'REQUIRES', 1, 1],
  ['TECH.SQL', 'TECH.API', 'REQUIRES', 1, 1],
  ['TECH.API', 'TECH.OPENDATA', 'REQUIRES', 1, 1],
  ['STAT.META', 'TECH.OPENDATA', 'REQUIRES', 1, 1],
  ['STAT.FOUND.DESC', 'TECH.VIZ', 'REQUIRES', 1, 1],
  ['TECH.PY.BASIC', 'TECH.VERSION', 'REQUIRES', 1, 1],
  ['TECH.SPREAD', 'TECH.GIS', 'REQUIRES', 1, 1],
  // governance
  ['GOVN.CYBER', 'GOVN.DSC', 'REQUIRES', 1, 1],
  ['GOVN.PRIVACY', 'GOVN.CONFID', 'REQUIRES', 1, 1],
  ['GOVN.CYBER', 'GOVN.CLOUD', 'REQUIRES', 1, 1],
  ['GOVN.CLOUD', 'GOVN.DPI', 'REQUIRES', 1, 1],
  ['GOVN.EOFFICE', 'GOVN.PROCURE', 'REQUIRES', 1, 1],
  ['GOVN.RTI', 'GOVN.AUDIT', 'REQUIRES', 1, 1],
  // behavioural
  ['BEHV.COMM', 'BEHV.PRESENT', 'REQUIRES', 1, 1],
  ['BEHV.COMM', 'BEHV.STAKE', 'REQUIRES', 1, 1],
  ['BEHV.TIME', 'BEHV.PM', 'REQUIRES', 1, 1],
  ['BEHV.PM', 'BEHV.LEAD', 'REQUIRES', 1, 1],
  ['BEHV.LEAD', 'BEHV.CHANGE', 'REQUIRES', 1, 1],
  ['BEHV.LEAD', 'BEHV.TRAIN', 'REQUIRES', 1, 1],
  ['BEHV.ETHICS', 'BEHV.DECIDE', 'REQUIRES', 1, 1],
];

// ── role profiles ────────────────────────────────────────────────────────
export interface RoleSeed {
  id: string;
  titleEn: string;
  cadre: string;
  description: string;
  // [competencyId, targetLevel, criticality, rationale]
  requires: [string, number, number, string][];
}

export const ROLES: RoleSeed[] = [
  {
    id: 'ROLE.JSO', titleEn: 'Junior Statistical Officer (Field)', cadre: 'Subordinate Statistical Service',
    description: 'Primary data collection in the field; scrutiny and first-level validation of schedules.',
    requires: [
      ['STAT.SURV.FIELD', 3, 3, 'Field collection is the core of the post.'],
      ['STAT.SURV.QUEST', 2, 3, 'Must interpret the schedule correctly to enumerate it.'],
      ['STAT.SAMP.BASIC', 2, 3, 'Must understand the frame and selection to follow it faithfully.'],
      ['STAT.FOUND.DESC', 2, 2, 'Needed for first-level scrutiny of collected data.'],
      ['TECH.SPREAD', 3, 2, 'Daily tool for schedule tabulation and returns.'],
      ['GOVN.PRIVACY', 2, 3, 'Handles personally identifiable respondent data.'],
      ['GOVN.CONFID', 2, 3, 'Statutory confidentiality of returns applies directly.'],
      ['BEHV.COMM', 2, 2, 'Reports to supervisors and deals with respondents.'],
      ['TECH.PY.BASIC', 1, 1, 'Emerging requirement as collection moves to CAPI and scripted validation.'],
    ],
  },
  {
    id: 'ROLE.SSO', titleEn: 'Senior Statistical Officer', cadre: 'Subordinate Statistical Service',
    description: 'Supervises field operations, processes and tabulates survey returns, prepares division outputs.',
    requires: [
      ['STAT.SURV.FIELD', 3, 3, 'Supervises enumerator teams.'],
      ['STAT.SAMP.STRAT', 3, 3, 'Implements and checks the sample design in the division.'],
      ['STAT.SAMP.WEIGHT', 2, 3, 'Applies design weights when producing division estimates.'],
      ['STAT.SURV.NONRESP', 2, 2, 'Manages non-response and edits before tabulation.'],
      ['STAT.DQ', 2, 3, 'Owns the quality gate for division output.'],
      ['TECH.SPREAD', 3, 2, 'Primary tabulation tool.'],
      ['TECH.PY.DATA', 2, 2, 'Processing volumes now exceed what spreadsheets handle safely.'],
      ['TECH.SQL', 2, 2, 'Survey data now lands in a database, not a file share.'],
      ['GOVN.CONFID', 3, 3, 'Responsible for safe handling of unit-level data.'],
      ['BEHV.LEAD', 2, 2, 'Leads a field team.'],
      ['BEHV.PRESENT', 2, 2, 'Presents division results upward.'],
    ],
  },
  {
    id: 'ROLE.ASO', titleEn: 'Assistant Statistical Officer (State DES)', cadre: 'State Statistical Service',
    description: 'State-level compilation of statistics and coordination with district offices.',
    requires: [
      ['STAT.FOUND.DESC', 3, 3, 'Core compilation work.'],
      ['STAT.SAMP.BASIC', 2, 2, 'Interprets central survey designs for state use.'],
      ['STAT.AGRI', 2, 2, 'State DES compiles agricultural statistics.'],
      ['STAT.META', 2, 2, 'Documents state series for central transmission.'],
      ['TECH.SPREAD', 3, 3, 'Primary tool.'],
      ['TECH.SQL', 2, 2, 'State data warehouse work.'],
      ['GOVN.EOFFICE', 2, 2, 'All state file work is now digital.'],
      ['BEHV.STAKE', 3, 3, 'Coordinates across district offices and line departments.'],
      ['BEHV.COMM', 3, 2, 'Heavy correspondence load.'],
    ],
  },
  {
    id: 'ROLE.ISS.PROB', titleEn: 'Indian Statistical Service — Probationer', cadre: 'Indian Statistical Service',
    description: 'Officer under probationary training; broad exposure across statistical and technical domains.',
    requires: [
      ['STAT.FOUND.INFER', 3, 3, 'Foundation of the service.'],
      ['STAT.SAMP.STRAT', 3, 3, 'Core methodology taught in probation.'],
      ['STAT.SAMP.CLUSTER', 2, 3, 'NSS designs are multistage.'],
      ['STAT.SURV.DESIGN', 2, 3, 'Expected to design surveys within a few years.'],
      ['STAT.NATACC.BASIC', 2, 2, 'Broad exposure requirement.'],
      ['STAT.PRICE.CPI', 2, 2, 'Broad exposure requirement.'],
      ['TECH.PY.DATA', 2, 2, 'Modern analytical toolchain.'],
      ['TECH.R.SURVEY', 2, 2, 'Complex survey estimation.'],
      ['GOVN.PRIVACY', 2, 2, 'Statutory obligation.'],
      ['BEHV.ETHICS', 3, 3, 'Professional independence is a service value.'],
      ['BEHV.COMM', 3, 2, 'Drafting is a daily task.'],
    ],
  },
  {
    id: 'ROLE.DD', titleEn: 'Deputy Director (Statistics)', cadre: 'Indian Statistical Service',
    description: 'Runs a statistical division: methodology decisions, output quality, team management.',
    requires: [
      ['STAT.SURV.DESIGN', 3, 3, 'Signs off division survey designs.'],
      ['STAT.SAMP.WEIGHT', 3, 3, 'Accountable for published estimates.'],
      ['STAT.DQ', 3, 3, 'Owns quality of division output.'],
      ['STAT.SURV.NONRESP', 3, 2, 'Adjudicates editing and imputation policy.'],
      ['STAT.META', 2, 2, 'Division output must be documented for dissemination.'],
      ['TECH.PY.DATA', 2, 2, 'Must be able to interrogate the division pipeline.'],
      ['TECH.VIZ', 2, 2, 'Output presentation.'],
      ['GOVN.AUDIT', 2, 3, 'Answers audit observations for the division.'],
      ['GOVN.CONFID', 3, 3, 'Accountable for microdata release decisions.'],
      ['BEHV.LEAD', 3, 3, 'Manages the division.'],
      ['BEHV.PM', 3, 3, 'Delivers survey rounds to deadline.'],
      ['BEHV.DECIDE', 3, 2, 'Methodology decisions must be defensible.'],
    ],
  },
  {
    id: 'ROLE.JD.METH', titleEn: 'Joint Director (Methodology)', cadre: 'Indian Statistical Service',
    description: 'Sets methodology standards, evaluates new techniques, represents MoSPI in technical fora.',
    requires: [
      ['STAT.SURV.DESIGN', 4, 3, 'Sets the standard for others.'],
      ['STAT.SAMP.WEIGHT', 4, 3, 'Adjudicates estimation methodology.'],
      ['STAT.DQ', 4, 3, 'Owns the quality framework.'],
      ['STAT.META', 3, 3, 'Standards ownership.'],
      ['STAT.SDG', 3, 3, 'International reporting obligations.'],
      ['TECH.ML.APPLIED', 2, 2, 'Must evaluate ML proposals for statistical production.'],
      ['BEHV.CHANGE', 3, 3, 'Introduces new methods into an established office.'],
      ['BEHV.TRAIN', 3, 2, 'Develops methodological capacity across the system.'],
      ['BEHV.STAKE', 3, 3, 'Represents MoSPI externally.'],
    ],
  },
  {
    id: 'ROLE.PRICE', titleEn: 'Price Statistics Officer', cadre: 'Indian Statistical Service',
    description: 'Compiles and quality-assures consumer and producer price indices.',
    requires: [
      ['STAT.PRICE.CPI', 3, 3, 'The core of the post.'],
      ['STAT.PRICE.WPI', 3, 3, 'The core of the post.'],
      ['STAT.SAMP.BASIC', 2, 2, 'Price collection is a sample.'],
      ['STAT.DQ', 3, 3, 'Price series are market-sensitive; errors are costly.'],
      ['STAT.META', 2, 2, 'Series documentation for release.'],
      ['TECH.PY.DATA', 2, 2, 'Index compilation is scripted.'],
      ['TECH.VIZ', 2, 2, 'Release charts.'],
      ['BEHV.ETHICS', 3, 3, 'Pre-release access to market-sensitive figures.'],
    ],
  },
  {
    id: 'ROLE.NATACC', titleEn: 'National Accounts Officer', cadre: 'Indian Statistical Service',
    description: 'Compiles national accounts aggregates and manages base year revision work.',
    requires: [
      ['STAT.NATACC.GDP', 3, 3, 'The core of the post.'],
      ['STAT.NATACC.BASIC', 3, 3, 'The core of the post.'],
      ['STAT.PRICE.WPI', 2, 3, 'Deflation depends on it.'],
      ['STAT.INDUS.ASI', 2, 2, 'A major source for GVA.'],
      ['STAT.DQ', 3, 3, 'Aggregates are heavily scrutinised.'],
      ['TECH.PY.DATA', 2, 2, 'Compilation pipeline.'],
      ['BEHV.PRESENT', 3, 2, 'Explains revisions publicly.'],
    ],
  },
  {
    id: 'ROLE.DATAENG', titleEn: 'Statistical Data Engineer', cadre: 'IT / NIC deputation',
    description: 'Builds and runs the data pipelines and platforms behind statistical production.',
    requires: [
      ['TECH.SQL', 3, 3, 'Core of the post.'],
      ['TECH.PY.DATA', 3, 3, 'Core of the post.'],
      ['TECH.BIGDATA', 3, 2, 'Volumes require it.'],
      ['TECH.CLOUD', 3, 2, 'Systems are moving to government cloud.'],
      ['TECH.API', 3, 3, 'Integration is the job.'],
      ['TECH.VERSION', 3, 3, 'Reproducibility is a statutory-grade requirement here.'],
      ['GOVN.CYBER', 3, 3, 'Runs systems holding confidential returns.'],
      ['GOVN.CLOUD', 2, 2, 'Empanelment and hosting constraints.'],
      ['STAT.META', 2, 2, 'Pipelines must emit standards-compliant metadata.'],
      ['STAT.DQ', 2, 3, 'Builds the automated quality gates.'],
    ],
  },
  {
    id: 'ROLE.TRAINER', titleEn: 'NSSTA Faculty', cadre: 'Indian Statistical Service',
    description: 'Designs and delivers training for the national statistical system.',
    requires: [
      ['BEHV.TRAIN', 4, 3, 'The core of the post.'],
      ['BEHV.PRESENT', 3, 3, 'The core of the post.'],
      ['STAT.SURV.DESIGN', 3, 3, 'Teaches the methodology.'],
      ['STAT.SAMP.STRAT', 3, 3, 'Teaches the methodology.'],
      ['TECH.PY.DATA', 2, 2, 'Course content increasingly requires it.'],
      ['TECH.VIZ', 2, 2, 'Teaching materials.'],
      ['STAT.DQ', 3, 2, 'Teaches the quality framework.'],
      ['BEHV.CHANGE', 2, 2, 'Training is how change is delivered.'],
    ],
  },
];

// ── courses ──────────────────────────────────────────────────────────────
// [id, name, provider, durationMins, level, competencyIds[], completionRate, tpac]
type CourseTuple = [string, string, 'iGOT' | 'NSSTA' | 'TPAC', number, string, string[], number, boolean];

export const COURSES: CourseTuple[] = [
  ['do_stat_desc_101', 'Foundations of Statistics for Government Officials', 'iGOT', 240, 'L2', ['STAT.FOUND.DESC'], 0.78, false],
  ['do_stat_prob_201', 'Probability and Distributions', 'iGOT', 300, 'L2', ['STAT.FOUND.PROB'], 0.62, false],
  ['do_stat_infer_301', 'Statistical Inference in Practice', 'NSSTA', 1080, 'L3', ['STAT.FOUND.INFER'], 0.71, true],
  ['do_samp_basic_101', 'Introduction to Sampling Methods', 'iGOT', 360, 'L2', ['STAT.SAMP.BASIC', 'STAT.SAMP.SRS'], 0.69, false],
  ['do_samp_strat_301', 'Stratified and Multistage Sampling Designs', 'NSSTA', 1440, 'L3', ['STAT.SAMP.STRAT', 'STAT.SAMP.CLUSTER'], 0.64, true],
  ['do_samp_weight_301', 'Weighting, Calibration and Variance Estimation', 'NSSTA', 1200, 'L3', ['STAT.SAMP.WEIGHT'], 0.55, true],
  ['do_surv_design_301', 'Designing a Statistical Survey End to End', 'NSSTA', 1800, 'L3', ['STAT.SURV.DESIGN', 'STAT.SURV.QUEST'], 0.58, true],
  ['do_surv_field_201', 'Field Operations and Enumerator Supervision', 'NSSTA', 900, 'L2', ['STAT.SURV.FIELD'], 0.81, false],
  ['do_surv_nonresp_301', 'Editing, Imputation and Non-response', 'NSSTA', 720, 'L3', ['STAT.SURV.NONRESP'], 0.60, false],
  ['do_natacc_101', 'System of National Accounts: Concepts', 'NSSTA', 1200, 'L2', ['STAT.NATACC.BASIC'], 0.66, true],
  ['do_natacc_301', 'GDP Compilation and Base Year Revision', 'NSSTA', 1800, 'L3', ['STAT.NATACC.GDP'], 0.52, true],
  ['do_price_cpi_201', 'Consumer Price Index: Compilation Practice', 'NSSTA', 960, 'L2', ['STAT.PRICE.CPI'], 0.70, true],
  ['do_price_wpi_201', 'Producer and Wholesale Price Indices', 'NSSTA', 720, 'L2', ['STAT.PRICE.WPI'], 0.68, false],
  ['do_labour_plfs_201', 'Labour Force Statistics and the PLFS', 'NSSTA', 900, 'L2', ['STAT.LABOUR.PLFS'], 0.63, true],
  ['do_agri_201', 'Agricultural Statistics and Crop Estimation', 'NSSTA', 720, 'L2', ['STAT.AGRI'], 0.72, false],
  ['do_indus_asi_201', 'Annual Survey of Industries: Concepts and Processing', 'NSSTA', 840, 'L2', ['STAT.INDUS.ASI'], 0.65, false],
  ['do_sdg_201', 'SDG National Indicator Framework', 'iGOT', 300, 'L2', ['STAT.SDG'], 0.74, false],
  ['do_meta_201', 'Statistical Metadata: SDMX and DDI', 'iGOT', 420, 'L2', ['STAT.META'], 0.49, false],
  ['do_dq_201', 'Data Quality Assurance Framework', 'iGOT', 360, 'L2', ['STAT.DQ'], 0.71, false],
  ['do_excel_101', 'Advanced Spreadsheets for Statistical Work', 'iGOT', 300, 'L2', ['TECH.SPREAD'], 0.86, false],
  ['do_python_101', 'Python Programming: Foundations', 'iGOT', 720, 'L2', ['TECH.PY.BASIC'], 0.57, false],
  ['do_python_data_201', 'Data Analysis with pandas', 'iGOT', 900, 'L2', ['TECH.PY.DATA'], 0.44, false],
  ['do_r_101', 'R for Statistical Computing', 'iGOT', 660, 'L2', ['TECH.R.BASIC'], 0.51, false],
  ['do_r_survey_301', 'Complex Survey Analysis in R', 'NSSTA', 900, 'L3', ['TECH.R.SURVEY'], 0.47, true],
  ['do_sql_101', 'SQL for Data Analysis', 'iGOT', 480, 'L2', ['TECH.SQL'], 0.66, false],
  ['do_gis_201', 'GIS and Spatial Analysis for Statistics', 'iGOT', 720, 'L2', ['TECH.GIS'], 0.53, false],
  ['do_viz_201', 'Communicating Data Visually', 'iGOT', 360, 'L2', ['TECH.VIZ', 'BEHV.PRESENT'], 0.75, false],
  ['do_ml_101', 'Machine Learning Foundations', 'iGOT', 900, 'L2', ['TECH.ML.BASIC'], 0.38, false],
  ['do_ml_stat_301', 'AI and ML in Official Statistics', 'NSSTA', 1200, 'L3', ['TECH.ML.APPLIED'], 0.41, true],
  ['do_bigdata_201', 'Big Data Technologies for Government', 'iGOT', 720, 'L2', ['TECH.BIGDATA'], 0.45, false],
  ['do_cloud_101', 'Cloud Computing Essentials', 'iGOT', 480, 'L2', ['TECH.CLOUD'], 0.68, false],
  ['do_api_101', 'APIs and Data Exchange Standards', 'iGOT', 360, 'L2', ['TECH.API'], 0.59, false],
  ['do_opendata_201', 'Open Data Publication and NDAP', 'iGOT', 300, 'L2', ['TECH.OPENDATA'], 0.64, false],
  ['do_git_101', 'Version Control and Reproducible Analysis', 'iGOT', 300, 'L2', ['TECH.VERSION'], 0.55, false],
  ['do_cyber_101', 'Cyber Security Awareness for Government Employees', 'iGOT', 180, 'L2', ['GOVN.CYBER'], 0.91, false],
  ['do_dpdp_101', 'Digital Personal Data Protection Act 2023', 'iGOT', 240, 'L2', ['GOVN.PRIVACY'], 0.83, false],
  ['do_confid_201', 'Statistical Confidentiality and Disclosure Control', 'NSSTA', 480, 'L2', ['GOVN.CONFID'], 0.67, false],
  ['do_dsc_101', 'Digital Signatures and e-Sign', 'iGOT', 120, 'L2', ['GOVN.DSC'], 0.88, false],
  ['do_meghraj_101', 'Government Cloud (MeghRaj) Overview', 'iGOT', 180, 'L2', ['GOVN.CLOUD'], 0.79, false],
  ['do_dpi_101', 'Digital Public Infrastructure and India Stack', 'iGOT', 240, 'L2', ['GOVN.DPI'], 0.72, false],
  ['do_rti_101', 'RTI Act and Records Management', 'iGOT', 240, 'L2', ['GOVN.RTI'], 0.84, false],
  ['do_eoffice_101', 'e-Office: Digital File Handling', 'iGOT', 180, 'L2', ['GOVN.EOFFICE'], 0.89, false],
  ['do_gem_101', 'Procurement through GeM', 'iGOT', 240, 'L2', ['GOVN.PROCURE'], 0.76, false],
  ['do_audit_201', 'Audit Readiness and Compliance', 'iGOT', 300, 'L2', ['GOVN.AUDIT'], 0.70, false],
  ['do_writing_101', 'Official Noting and Drafting', 'iGOT', 240, 'L2', ['BEHV.COMM'], 0.85, false],
  ['do_lead_201', 'Leading Teams in Government', 'iGOT', 480, 'L2', ['BEHV.LEAD'], 0.73, false],
  ['do_pm_201', 'Project Management for Government Projects', 'iGOT', 600, 'L2', ['BEHV.PM'], 0.61, false],
  ['do_ethics_101', 'Fundamental Principles of Official Statistics', 'NSSTA', 240, 'L2', ['BEHV.ETHICS'], 0.80, false],
  ['do_decide_201', 'Evidence-Based Decision Making', 'iGOT', 360, 'L2', ['BEHV.DECIDE'], 0.69, false],
  ['do_change_201', 'Managing Change in Public Organisations', 'iGOT', 420, 'L2', ['BEHV.CHANGE'], 0.58, false],
  ['do_stake_201', 'Inter-departmental Coordination', 'iGOT', 300, 'L2', ['BEHV.STAKE'], 0.74, false],
  ['do_train_301', 'Training of Trainers', 'NSSTA', 1440, 'L3', ['BEHV.TRAIN'], 0.66, true],
  ['do_time_101', 'Work Planning and Prioritisation', 'iGOT', 180, 'L2', ['BEHV.TIME'], 0.87, false],
];

// ── survey / activity calendar (drives gap urgency) ──────────────────────
// [name, owner, startsInDays, durationDays, competencyIds, headcount]
export const CALENDAR: [string, string, number, number, string[], number][] = [
  ['PLFS 2026–27 field round briefing', 'NSSO (FOD)', 34, 60, ['STAT.SURV.FIELD', 'STAT.SAMP.CLUSTER', 'STAT.LABOUR.PLFS'], 420],
  ['CPI base year revision — item basket review', 'Price Statistics Division', 61, 120, ['STAT.PRICE.CPI', 'STAT.PRICE.WPI', 'STAT.META'], 65],
  ['Annual Survey of Industries returns processing', 'ISW Division', 20, 90, ['STAT.INDUS.ASI', 'TECH.SQL', 'STAT.DQ'], 140],
  ['SDG National Indicator Framework — 2027 reporting cycle', 'SDG Cell', 75, 150, ['STAT.SDG', 'STAT.META', 'TECH.OPENDATA'], 55],
  ['NDAP dataset onboarding sprint', 'Data Informatics Division', 45, 60, ['TECH.OPENDATA', 'TECH.API', 'STAT.META'], 38],
  ['ML-assisted editing pilot — HCES', 'Methodology Division', 88, 120, ['TECH.ML.APPLIED', 'STAT.SURV.NONRESP', 'STAT.DQ'], 24],
  ['GDP base year revision preparatory work', 'National Accounts Division', 120, 240, ['STAT.NATACC.GDP', 'STAT.PRICE.WPI', 'STAT.INDUS.ASI'], 46],
];
